# Generated by Django 4.2 on 2023-06-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('necessidade_solo', models.CharField(max_length=100)),
                ('acidez_solo', models.CharField(max_length=100)),
                ('exposicao_solar', models.CharField(max_length=100)),
                ('estacao_producao', models.CharField(max_length=100)),
                ('irrigacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Minerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposicao_solar', models.CharField(max_length=100)),
                ('irrigacao', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.especies')),
                ('estacao_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.estacao')),
                ('solo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.solo')),
            ],
        ),
        migrations.CreateModel(
            name='EspeciesMinerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.especies')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.minerais')),
            ],
        ),
    ]
