# Generated by Django 4.2 on 2023-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='nome_cientifico',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
