# Generated by Django 4.2 on 2023-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0002_especies_nome_cientifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='imagem_especie',
            field=models.ImageField(null=True, upload_to='imagens/especies/'),
        ),
        migrations.AddField(
            model_name='especies',
            name='imagem_fruta',
            field=models.ImageField(null=True, upload_to='imagens/frutas/'),
        ),
    ]
