# Generated by Django 4.2 on 2023-06-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0003_especies_imagem_especie_especies_imagem_fruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='icon_estacao',
            field=models.ImageField(null=True, upload_to='imagens/icon_estacao/'),
        ),
        migrations.AddField(
            model_name='minerais',
            name='icon_mineral',
            field=models.ImageField(null=True, upload_to='imagens/icon_minerais/'),
        ),
        migrations.AddField(
            model_name='solo',
            name='icon_solo',
            field=models.ImageField(null=True, upload_to='imagens/icon_solo/'),
        ),
    ]
