# Generated by Django 4.2 on 2023-06-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0004_estacao_icon_estacao_minerais_icon_mineral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='estacao_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.estacao'),
        ),
    ]
