# Generated by Django 4.2 on 2023-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0005_alter_especies_estacao_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icon_PH', models.ImageField(null=True, upload_to='imagens/icon_PH/')),
            ],
        ),
    ]
