# Generated by Django 4.2 on 2023-06-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0006_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='acidez_solo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.ph'),
        ),
        migrations.AlterField(
            model_name='especies',
            name='necessidade_solo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.solo'),
        ),
    ]
