# Generated by Django 4.2 on 2023-06-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0007_alter_especies_acidez_solo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icon_irrigacao', models.ImageField(null=True, upload_to='imagens/icon_Irrigacao/')),
            ],
        ),
    ]
