# Generated by Django 4.2 on 2023-06-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0008_irrigacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposicaoSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icon_exposicaosolar', models.ImageField(null=True, upload_to='imagens/icon_exposicao_solar/')),
            ],
        ),
        migrations.AlterField(
            model_name='especies',
            name='irrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.irrigacao'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='irrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.irrigacao'),
        ),
    ]
