# Generated by Django 4.2 on 2023-06-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0009_exposicaosolar_alter_especies_irrigacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='exposicao_solar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.exposicaosolar'),
        ),
    ]
