# Generated by Django 4.2 on 2023-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0010_alter_especies_exposicao_solar'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='detalhes',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
