# Generated by Django 4.2 on 2023-06-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0013_user_icon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon_user',
        ),
    ]
