# Generated by Django 4.2 on 2023-06-30 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0014_remove_user_icon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantas',
            name='dt_plantio',
            field= models.DateField(),
            preserve_default=False,
        ),
    
        migrations.AlterField(
            model_name='plantas',
            name='exposicao_solar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.exposicaosolar'),
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ultima_producao', models.DateField()),
                ('frequencia_producao', models.IntegerField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.plantas')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ultima_fertilizacao', models.DateField()),
                ('ultima_medicao_ph', models.DateField()),
                ('ultimo_ph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dt_ultima_poda', models.DateField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.plantas')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_evento', models.DateField()),
                ('informacoes', models.TextField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.plantas')),
            ],
        ),
    ]
