# Generated by Django 4.2 on 2023-06-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0015_plantas_usuario_alter_plantas_exposicao_solar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantas',
            old_name='exposicao_solar',
            new_name='exposicao_solar_atual',
        ),
        migrations.AddField(
            model_name='plantas',
            name='acidez_solo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PIECE.ph'),
            preserve_default=False,
        ),
    ]
