# Generated by Django 4.2 on 2023-06-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0017_alter_manutencao_ultimo_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='exposicao_solar_atual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PIECE.exposicaosolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='solo_atual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PIECE.solo'),
            preserve_default=False,
        ),
    ]
