# Generated by Django 4.2 on 2023-07-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0018_manutencao_exposicao_solar_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ultima_fertilizacao', models.DateField(blank=True, null=True)),
                ('ultima_medicao_ph', models.DateField(blank=True, null=True)),
                ('dt_ultima_poda', models.DateField(blank=True, null=True)),
                ('dt_ultima_producao', models.DateField(blank=True, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIECE.plantas')),
            ],
        ),
    ]
