# Generated by Django 4.2 on 2023-07-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0018_manutencao_exposicao_solar_atual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantas',
            name='dt_plantio',
        ),
    ]
