# Generated by Django 4.2 on 2023-07-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0019_historicodatas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='frequencia_producao',
        ),
    ]
