# Generated by Django 4.2 on 2023-07-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0020_remove_producao_frequencia_producao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
