# Generated by Django 4.2 on 2023-07-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0021_delete_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicodatas',
            name='Solo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PIECE.solo'),
        ),
        migrations.AddField(
            model_name='historicodatas',
            name='exposicao_solar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PIECE.exposicaosolar'),
        ),
        migrations.AddField(
            model_name='historicodatas',
            name='ultimo_ph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PIECE.ph'),
        ),
        migrations.AddField(
            model_name='producao',
            name='estacao_ultima_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PIECE.estacao'),
        ),
    ]
