# Generated by Django 4.2 on 2023-07-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIECE', '0022_historicodatas_solo_historicodatas_exposicao_solar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicodatas',
            name='Estacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PIECE.estacao'),
        ),
    ]
